services:
  db:
    container_name: postgres_container0
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
